Update Nginx Container
isomerpages/isomer-redirection pull request #142
Opened 2021-03-15 19:47 UTC by JonasAlfredsson

The latest version of the container contains a fix for an issue which 
would hinder startup scripts from runing.

[1]: https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/21

2021-03-15 19:48 UTC, JonasAlfredsson commented
From what I gathered you needed a [short sleep](https://github.com/isomerpages/isomer-redirection/blob/staging/00-sleeper.sh) or else AWS would kill the container? 
However, a super obvious bug from my side made so that this script would never be triggered. This is now fixed, but you were able to run this either way?

2021-03-16 00:05 UTC, LoneRifle commented
> From what I gathered you needed a [short sleep](https://github.com/isomerpages/isomer-redirection/blob/staging/00-sleeper.sh) or else AWS would kill the container?
> However, a super obvious bug from my side made so that this script would never be triggered. This is now fixed, but you were able to run this either way?

Hi @JonasAlfredsson ! We were indeed able to run it either way. I was mistaken the last time - we may not have needed the short sleep after all, as AWS was terminating the container due to missing configuration in nginx that was needed for long `server` entries.

2021-03-16 00:06 UTC, LoneRifle requested changes
Could you base your changes off staging please? That's our default branch, not staging.

2021-03-16 01:53 UTC, JonasAlfredsson commented
Yes, no problem. However, I had to create an entirely [new request][1], so I will close this one. 

[1]: https://github.com/isomerpages/isomer-redirection/pull/143

2021-03-16 01:53 UTC, closed without merging